name: github_actions_importer
on:  
  push:
    branches: [ "main" ]
  workflow_dispatch:
defaults:
  run:
    shell: bash
env:
  GITHUB_INSTANCE_URL: ${{ dev.GH_INSTANCE_URL || 'https://github.com' }}
  GITHUB_ACCESS_TOKEN: ${{ dev.GH_ACCESS_TOKEN }}
  JENKINS_INSTANCE_URL: ${{ dev.JENKINS_INSTANCE_URL }}
  JENKINS_USERNAME: ${{ dev.jenkins_username }}
  JENKINS_ACCESS_TOKEN: ${{ dev.jenkins_access_token }}

jobs:
  execute-actions-importer:
    runs-on:
      - ubuntu-latest
    outputs:
      command: ${{ steps.prepare.outputs.command }}
      log-filename: ${{ steps.logs.outputs.filename }}
    steps:
      - name: Install GitHub Actions Importer
        run: |
          gh actions-importer version || gh extension install github/gh-actions-importer
          gh actions-importer update
        env:
          GH_TOKEN: ${{ github.token }}
